export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      images: {
        Row: {
          id: string;
          type: string;
          url: string;
          title: string;
          description: string;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Insert: {
          id: string;
          type: string;
          url: string;
          title?: string;
          description?: string;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Update: {
          id?: string;
          type?: string;
          url?: string;
          title?: string;
          description?: string;
          date?: string;
          consultation_id?: string;
          created_at?: string;
        };
      };
      consultations: {
        Row: {
          id: string;
          date: string;
          notes: string;
          diagnosis: string;
          prescription: string;
          duration: number;
          clinical_exam: string;
          dilatation_required: boolean;
          left_eye: any;
          right_eye: any;
          detailed_clinical_exam: any;
          secretary_needed: boolean;
          secretary_note: string;
          follow_up: boolean;
          consultation_type: string;
          created_at: string;
          updated_at: string;
          patient_id: string;
          tonometrie_data: any;
          consultation_reason: string;
          inspection_od_og: any;
          diagnosis_od_og: any;
          general_medical_history: string;
          ophthalmological_history: string;
          motility_exam: string;
          gonioscopy_notes: string;
          medical_imaging_notes: string;
          motility_exam_od_og: any;
          treatment_plan_od_og: any;
          anterior_segment_od_og: any;
          fundus_od_og: any;
          next_appointment: any;
          contact_lens_data: any;
          medical_imaging_data: any;
          tonometrie_left_eye: any;
          tonometrie_right_eye: any;
          documents_data: any;
          type: number;
        };
        Insert: {
          id: string;
          date: string;
          notes?: string;
          diagnosis?: string;
          prescription?: string;
          duration?: number;
          clinical_exam?: string;
          dilatation_required?: boolean;
          left_eye?: any;
          right_eye?: any;
          detailed_clinical_exam?: any;
          secretary_needed?: boolean;
          secretary_note?: string;
          follow_up?: boolean;
          consultation_type?: string;
          created_at: string;
          updated_at: string;
          patient_id: string;
          tonometrie_data?: any;
          consultation_reason?: string;
          inspection_od_og?: any;
          diagnosis_od_og?: any;
          general_medical_history?: string;
          ophthalmological_history?: string;
          motility_exam?: string;
          gonioscopy_notes?: string;
          medical_imaging_notes?: string;
          motility_exam_od_og?: any;
          treatment_plan_od_og?: any;
          anterior_segment_od_og?: any;
          fundus_od_og?: any;
          next_appointment?: any;
          contact_lens_data?: any;
          medical_imaging_data?: any;
          tonometrie_left_eye?: any;
          tonometrie_right_eye?: any;
          documents_data?: any;
          type: number;
        };
        Update: {
          id?: string;
          date?: string;
          notes?: string;
          diagnosis?: string;
          prescription?: string;
          duration?: number;
          clinical_exam?: string;
          dilatation_required?: boolean;
          left_eye?: any;
          right_eye?: any;
          detailed_clinical_exam?: any;
          secretary_needed?: boolean;
          secretary_note?: string;
          follow_up?: boolean;
          consultation_type?: string;
          created_at?: string;
          updated_at?: string;
          patient_id?: string;
          tonometrie_data?: any;
          consultation_reason?: string;
          inspection_od_og?: any;
          diagnosis_od_og?: any;
          general_medical_history?: string;
          ophthalmological_history?: string;
          motility_exam?: string;
          gonioscopy_notes?: string;
          medical_imaging_notes?: string;
          motility_exam_od_og?: any;
          treatment_plan_od_og?: any;
          anterior_segment_od_og?: any;
          fundus_od_og?: any;
          next_appointment?: any;
          contact_lens_data?: any;
          medical_imaging_data?: any;
          tonometrie_left_eye?: any;
          tonometrie_right_eye?: any;
          documents_data?: any;
          type?: number;
        };
      };
      contacts: {
        Row: {
          id: number;
          type: string;
          name: string;
          specialization: string;
          organization: string;
          phone: string;
          mobile: string;
          fax: string;
          email: string;
          website: string;
          emergency_phone: string;
          address: any;
          schedule: any;
          services: Json;
          notes: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          type: string;
          name: string;
          specialization?: string;
          organization?: string;
          phone?: string;
          mobile?: string;
          fax?: string;
          email?: string;
          website?: string;
          emergency_phone?: string;
          address?: any;
          schedule?: any;
          services?: Json;
          notes?: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Update: {
          id?: number;
          type?: string;
          name?: string;
          specialization?: string;
          organization?: string;
          phone?: string;
          mobile?: string;
          fax?: string;
          email?: string;
          website?: string;
          emergency_phone?: string;
          address?: any;
          schedule?: any;
          services?: Json;
          notes?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      medicines: {
        Row: {
          id: string;
          medication_name: string;
          strength: string;
          type: string;
          packaging: string;
          instructions: string;
          category: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          medication_name: string;
          strength?: string;
          type?: string;
          packaging?: string;
          instructions?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          medication_name?: string;
          strength?: string;
          type?: string;
          packaging?: string;
          instructions?: string;
          category?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      tarifs: {
        Row: {
          id: number;
          name: string;
          description: string;
          price: number;
          category: string;
          is_active: boolean;
          duration: number;
          code: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: number;
          name: string;
          description?: string;
          price: number;
          category: string;
          is_active: boolean;
          duration?: number;
          code?: string;
          created_at: string;
          updated_at: string;
        };
        Update: {
          id?: number;
          name?: string;
          description?: string;
          price?: number;
          category?: string;
          is_active?: boolean;
          duration?: number;
          code?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          title: string;
          start_time: string;
          end_time: string;
          patient_id: string;
          patient_name: string;
          notes: string;
          status: string;
          state: string;
          is_group: boolean;
          group_patient_ids: string;
          consultation_type: string;
          needs_dilation: boolean;
          is_dilated: boolean;
          dilation_status: string;
          dilation_completed_at: string;
          arrived_at: string;
          consultation_start: string;
          completed_at: string;
          payment_info: any;
          created_at: string;
          updated_at: string;
          dilation_type: string;
          type: number;
        };
        Insert: {
          id: string;
          title: string;
          start_time: string;
          end_time: string;
          patient_id?: string;
          patient_name?: string;
          notes?: string;
          status?: string;
          state?: string;
          is_group?: boolean;
          group_patient_ids?: string;
          consultation_type?: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_status?: string;
          dilation_completed_at?: string;
          arrived_at?: string;
          consultation_start?: string;
          completed_at?: string;
          payment_info?: any;
          created_at: string;
          updated_at: string;
          dilation_type?: string;
          type?: number;
        };
        Update: {
          id?: string;
          title?: string;
          start_time?: string;
          end_time?: string;
          patient_id?: string;
          patient_name?: string;
          notes?: string;
          status?: string;
          state?: string;
          is_group?: boolean;
          group_patient_ids?: string;
          consultation_type?: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_status?: string;
          dilation_completed_at?: string;
          arrived_at?: string;
          consultation_start?: string;
          completed_at?: string;
          payment_info?: any;
          created_at?: string;
          updated_at?: string;
          dilation_type?: string;
          type?: number;
        };
      };
      antecedents: {
        Row: {
          id: string;
          description: string;
          date: string;
          type: string;
          patient_id: string;
          created_at: string;
        };
        Insert: {
          id: string;
          description: string;
          date: string;
          type: string;
          patient_id: string;
          created_at: string;
        };
        Update: {
          id?: string;
          description?: string;
          date?: string;
          type?: string;
          patient_id?: string;
          created_at?: string;
        };
      };
      workflow_events: {
        Row: {
          id: string;
          event_type: string;
          patient_id: string;
          appointment_id: string;
          consultation_id: string;
          metadata: any;
          timestamp: string;
        };
        Insert: {
          id: string;
          event_type: string;
          patient_id?: string;
          appointment_id?: string;
          consultation_id?: string;
          metadata?: any;
          timestamp: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          patient_id?: string;
          appointment_id?: string;
          consultation_id?: string;
          metadata?: any;
          timestamp?: string;
        };
      };
      lentille_conv: {
        Row: {
          id: number;
          num_enr: number;
          idtab_conversion: number;
          lunettes: number;
          lun_plus: number;
          lun_moins: number;
        };
        Insert: {
          id: number;
          num_enr: number;
          idtab_conversion: number;
          lunettes: number;
          lun_plus?: number;
          lun_moins?: number;
        };
        Update: {
          id?: number;
          num_enr?: number;
          idtab_conversion?: number;
          lunettes?: number;
          lun_plus?: number;
          lun_moins?: number;
        };
      };
      todo_items: {
        Row: {
          id: string;
          text: string;
          is_completed: boolean;
          completed_at: string;
          date: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          text: string;
          is_completed?: boolean;
          completed_at?: string;
          date?: string;
          created_at: string;
          updated_at: string;
        };
        Update: {
          id?: string;
          text?: string;
          is_completed?: boolean;
          completed_at?: string;
          date?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          base_price: number;
          discount: number;
          is_free: boolean;
          total: number;
          paid: number;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Insert: {
          id: string;
          base_price: number;
          discount?: number;
          is_free?: boolean;
          total: number;
          paid?: number;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Update: {
          id?: string;
          base_price?: number;
          discount?: number;
          is_free?: boolean;
          total?: number;
          paid?: number;
          date?: string;
          consultation_id?: string;
          created_at?: string;
        };
      };
      waitlist_entries: {
        Row: {
          id: string;
          arrived_at: string;
          date: string;
          patient_id: string;
          needs_dilation: boolean;
          is_dilated: boolean;
          dilation_completed_at: string;
          dilation_status: string;
          state: string;
          consultation_start: string;
          completed_at: string;
          is_finished: boolean;
          notes: string;
          created_at: string;
          updated_at: string;
          dilation_type: string;
        };
        Insert: {
          id: string;
          arrived_at: string;
          date?: string;
          patient_id: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_completed_at?: string;
          dilation_status?: string;
          state?: string;
          consultation_start?: string;
          completed_at?: string;
          is_finished?: boolean;
          notes?: string;
          created_at: string;
          updated_at: string;
          dilation_type?: string;
        };
        Update: {
          id?: string;
          arrived_at?: string;
          date?: string;
          patient_id?: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_completed_at?: string;
          dilation_status?: string;
          state?: string;
          consultation_start?: string;
          completed_at?: string;
          is_finished?: boolean;
          notes?: string;
          created_at?: string;
          updated_at?: string;
          dilation_type?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          text: string;
          sender: string;
          timestamp: string;
          is_read: boolean;
          created_at: string;
        };
        Insert: {
          id: string;
          text: string;
          sender: string;
          timestamp: string;
          is_read?: boolean;
          created_at: string;
        };
        Update: {
          id?: string;
          text?: string;
          sender?: string;
          timestamp?: string;
          is_read?: boolean;
          created_at?: string;
        };
      };
      documents: {
        Row: {
          id: string;
          title: string;
          file_url: string;
          type: string;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Insert: {
          id: string;
          title: string;
          file_url: string;
          type: string;
          date: string;
          consultation_id: string;
          created_at: string;
        };
        Update: {
          id?: string;
          title?: string;
          file_url?: string;
          type?: string;
          date?: string;
          consultation_id?: string;
          created_at?: string;
        };
      };
      patients: {
        Row: {
          id: string;
          name: string;
          surname: string;
          dob: string;
          address: any;
          phone_number: string;
          phoneNumber: string;
          phone: string;
          email: string;
          blood_type: string;
          consultation_start: string;
          medical_history: string;
          needs_dilation: boolean;
          is_dilated: boolean;
          dilation_status: string;
          dilation_completed_at: string;
          consultation_data: any;
          payment_info: any;
          notes: string;
          created_at: string;
          updated_at: string;
          personne: string;
        };
        Insert: {
          id: string;
          name: string;
          surname: string;
          dob: string;
          address?: any;
          phone_number?: string;
          phoneNumber?: string;
          phone?: string;
          email?: string;
          blood_type?: string;
          consultation_start?: string;
          medical_history?: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_status?: string;
          dilation_completed_at?: string;
          consultation_data?: any;
          payment_info?: any;
          notes?: string;
          created_at: string;
          updated_at: string;
          personne?: string;
        };
        Update: {
          id?: string;
          name?: string;
          surname?: string;
          dob?: string;
          address?: any;
          phone_number?: string;
          phoneNumber?: string;
          phone?: string;
          email?: string;
          blood_type?: string;
          consultation_start?: string;
          medical_history?: string;
          needs_dilation?: boolean;
          is_dilated?: boolean;
          dilation_status?: string;
          dilation_completed_at?: string;
          consultation_data?: any;
          payment_info?: any;
          notes?: string;
          created_at?: string;
          updated_at?: string;
          personne?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}
