/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ['class'],
	content: ['./src/ui/**/*.{ts,tsx,js,jsx}'],
	theme: {
		container: {
			center: true,
			padding: '2rem',
			screens: {
				'2xl': '1400px',
			},
		},
		extend: {
			fontFamily: {
				sans: ['var(--font-sans)', 'sans-serif'],
			},
			fontSize: {
				xs: 'var(--text-xs)',
				sm: 'var(--text-sm)',
				base: 'var(--text-base)',
				lg: 'var(--text-lg)',
				xl: 'var(--text-xl)',
				'2xl': 'var(--text-2xl)',
				'3xl': 'var(--text-3xl)',
				'4xl': 'var(--text-4xl)',
			},
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
					50: 'hsl(var(--primary) / 0.1)',
					100: 'hsl(var(--primary) / 0.2)',
					200: 'hsl(var(--primary) / 0.3)',
					300: 'hsl(var(--primary) / 0.4)',
					400: 'hsl(var(--primary) / 0.5)',
					500: 'hsl(var(--primary) / 0.6)',
					600: 'hsl(var(--primary) / 0.7)',
					700: 'hsl(var(--primary) / 0.8)',
					800: 'hsl(var(--primary) / 0.9)',
					900: 'hsl(var(--primary) / 1)',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
					50: 'hsl(var(--secondary) / 0.1)',
					100: 'hsl(var(--secondary) / 0.2)',
					200: 'hsl(var(--secondary) / 0.3)',
					300: 'hsl(var(--secondary) / 0.4)',
					400: 'hsl(var(--secondary) / 0.5)',
					500: 'hsl(var(--secondary) / 0.6)',
					600: 'hsl(var(--secondary) / 0.7)',
					700: 'hsl(var(--secondary) / 0.8)',
					800: 'hsl(var(--secondary) / 0.9)',
					900: 'hsl(var(--secondary) / 1)',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				success: {
					50: 'hsl(var(--success))',
					100: 'hsl(var(--success))',
					200: 'hsl(var(--success))',
					300: 'hsl(var(--success))',
					400: 'hsl(var(--success))',
					500: 'hsl(var(--success))',
					600: 'hsl(var(--success))',
					700: 'hsl(var(--success))',
					800: 'hsl(var(--success))',
					900: 'hsl(var(--success))',
					DEFAULT: 'hsl(var(--success))',
					foreground: 'hsl(var(--success-foreground))',
				},
				warning: {
					50: 'hsl(var(--warning))',
					100: 'hsl(var(--warning))',
					200: 'hsl(var(--warning))',
					300: 'hsl(var(--warning))',
					400: 'hsl(var(--warning))',
					500: 'hsl(var(--warning))',
					600: 'hsl(var(--warning))',
					700: 'hsl(var(--warning))',
					800: 'hsl(var(--warning))',
					900: 'hsl(var(--warning))',
					DEFAULT: 'hsl(var(--warning))',
					foreground: 'hsl(var(--warning-foreground))',
				},
				danger: {
					50: 'hsl(var(--destructive))',
					100: 'hsl(var(--destructive))',
					200: 'hsl(var(--destructive))',
					300: 'hsl(var(--destructive))',
					400: 'hsl(var(--destructive))',
					500: 'hsl(var(--destructive))',
					600: 'hsl(var(--destructive))',
					700: 'hsl(var(--destructive))',
					800: 'hsl(var(--destructive))',
					900: 'hsl(var(--destructive))',
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				// Add default palette for mina-scheduler compatibility
				default: {
					50: 'hsl(var(--muted))',
					100: 'hsl(var(--muted))',
					200: 'hsl(var(--border))',
					300: 'hsl(var(--border))',
					400: 'hsl(var(--muted-foreground))',
					500: 'hsl(var(--muted-foreground))',
					600: 'hsl(var(--foreground))',
					700: 'hsl(var(--foreground))',
					800: 'hsl(var(--foreground))',
					900: 'hsl(var(--foreground))',
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			keyframes: {
				'accordion-down': {
					from: { height: '0' },
					to: { height: 'var(--radix-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--radix-accordion-content-height)' },
					to: { height: '0' },
				},
				'fade-in-up': {
					from: {
						opacity: '0',
						transform: 'translateY(20px)',
					},
					to: {
						opacity: '1',
						transform: 'translateY(0)',
					},
				},
				'fade-in': {
					from: { opacity: '0' },
					to: { opacity: '1' },
				},
				'slide-up': {
					from: {
						opacity: '0',
						transform: 'translateY(30px)',
					},
					to: {
						opacity: '1',
						transform: 'translateY(0)',
					},
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				'fade-in-up': 'fade-in-up 0.8s ease-out 0.2s forwards',
				'slide-up': 'slide-up 0.6s ease-out forwards',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
};

