/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as BookViewerRouteImport } from './routes/book-viewer'
import { Route as IndexRouteImport } from './routes/index'

const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const BookViewerRoute = BookViewerRouteImport.update({
  id: '/book-viewer',
  path: '/book-viewer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-viewer': typeof BookViewerRoute
  '/doctor': typeof DoctorRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-viewer': typeof BookViewerRoute
  '/doctor': typeof DoctorRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-viewer': typeof BookViewerRoute
  '/doctor': typeof DoctorRoute
  '/secretary': typeof SecretaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book-viewer' | '/doctor' | '/secretary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book-viewer' | '/doctor' | '/secretary'
  id: '__root__' | '/' | '/book-viewer' | '/doctor' | '/secretary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookViewerRoute: typeof BookViewerRoute
  DoctorRoute: typeof DoctorRoute
  SecretaryRoute: typeof SecretaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-viewer': {
      id: '/book-viewer'
      path: '/book-viewer'
      fullPath: '/book-viewer'
      preLoaderRoute: typeof BookViewerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookViewerRoute: BookViewerRoute,
  DoctorRoute: DoctorRoute,
  SecretaryRoute: SecretaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
